// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/MMLocM.proto

package edu.ucsf.tsf;

public final class MMLocM {
  private MMLocM() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(edu.ucsf.tsf.MMLocM.intensityAperture);
    registry.add(edu.ucsf.tsf.MMLocM.intensityBackground);
    registry.add(edu.ucsf.tsf.MMLocM.intensityRatio);
    registry.add(edu.ucsf.tsf.MMLocM.mSigma);
  }
  public static final int INTENSITY_APERTURE_FIELD_NUMBER = 1500;
  /**
   * <code>extend .TSF.Spot { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      edu.ucsf.tsf.TaggedSpotsProtos.Spot,
      java.lang.Float> intensityAperture = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Float.class,
        null);
  public static final int INTENSITY_BACKGROUND_FIELD_NUMBER = 1501;
  /**
   * <code>extend .TSF.Spot { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      edu.ucsf.tsf.TaggedSpotsProtos.Spot,
      java.lang.Float> intensityBackground = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Float.class,
        null);
  public static final int INTENSITY_RATIO_FIELD_NUMBER = 1502;
  /**
   * <code>extend .TSF.Spot { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      edu.ucsf.tsf.TaggedSpotsProtos.Spot,
      java.lang.Float> intensityRatio = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Float.class,
        null);
  public static final int M_SIGMA_FIELD_NUMBER = 1503;
  /**
   * <code>extend .TSF.Spot { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      edu.ucsf.tsf.TaggedSpotsProtos.Spot,
      java.lang.Float> mSigma = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Float.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020src/MMLocM.proto\032\022src/TSFProto.proto:&" +
      "\n\022intensity_aperture\022\t.TSF.Spot\030\334\013 \001(\002:(" +
      "\n\024intensity_background\022\t.TSF.Spot\030\335\013 \001(\002" +
      ":#\n\017intensity_ratio\022\t.TSF.Spot\030\336\013 \001(\002:\033\n" +
      "\007m_sigma\022\t.TSF.Spot\030\337\013 \001(\002B\016\n\014edu.ucsf.t" +
      "sf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          intensityAperture.internalInit(descriptor.getExtensions().get(0));
          intensityBackground.internalInit(descriptor.getExtensions().get(1));
          intensityRatio.internalInit(descriptor.getExtensions().get(2));
          mSigma.internalInit(descriptor.getExtensions().get(3));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          edu.ucsf.tsf.TaggedSpotsProtos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
