classdef mtsf
    %mtsf Matlab interface to tagged spot format
    %   The tagged spot format is an implementation of Google Protocols 
    %   Buffer to the storage of single molecule fitting data such as 
    %   used in super resolution techniques like
    %   STORM and PALM.  This matlab code interfaces to the Java
    %   code generated by Google Protocol Buffers based on tsf.proto
    
    properties
        applicationId
        boxSize
        imageFileName
        fitMode
        intensityUnits
        locationUnits
        nrSpots
        nrChannels
        nrFrames
        nrPixelsX
        nrPixelsY
        nrPos
        nrSlices
        pixelSize
        spotList
        fileName
    end
    
    methods
        % constructs mtsf object given the path to a tagged spot format
        % file
        function mt = mtsf(fileName)
            mt.fileName = fileName;
            fi = java.io.FileInputStream(mt.fileName);
            res = javaMethod('parseFrom', 'edu.ucsf.tsf.TaggedSpotsProtos$SpotList', fi);
            mt.spotList = res.getSpotList();
            mt.nrSpots = mt.spotList.size;
            if (res.hasApplicationId)
                mt.applicationId = res.getApplicationId;
            end
            if (res.hasBoxSize)
                mt.boxSize = res.getBoxSize;
            end
            if (res.hasFilepath)
                mt.imageFileName = char(res.getFilepath);
            end
            if (res.hasFitMode)
                if (res.getFitMode == javaMethod('valueOf','edu.ucsf.tsf.TaggedSpotsProtos$SpotList$FitMode', 0))
                    mt.fitMode = 'One Axis';                       
                end
                if (res.getFitMode == javaMethod('valueOf','edu.ucsf.tsf.TaggedSpotsProtos$SpotList$FitMode', 1))
                    mt.fitMode = 'Two Axis';                       
                end
                if (res.getFitMode == javaMethod('valueOf','edu.ucsf.tsf.TaggedSpotsProtos$SpotList$FitMode', 2))
                    mt.fitMode = 'Two Axis and Theta';                       
                end
            end
            if (res.hasIntensityUnits)
                if (res.getIntensityUnits == javaMethod('valueOf','edu.ucsf.tsf.TaggedSpotsProtos$SpotList$IntensityUnits', 0))
                    mt.intensityUnits = 'Counts';
                elseif (res.getIntensityUnits == javaMethod('valueOf','edu.ucsf.tsf.TaggedSpotsProtos$SpotList$IntensityUnits', 1))
                    mt.intensityUnits = 'Photons';
                end
            end
            if (res.hasLocationUnits)
                if (res.getLocationUnits == javaMethod('valueOf','edu.ucsf.tsf.TaggedSpotsProtos$SpotList$LocationUnits', 0))
                    mt.locationUnits = 'nm';
                elseif (res.getLocationUnits == javaMethod('valueOf','edu.ucsf.tsf.TaggedSpotsProtos$SpotList$LocationUnits', 1))
                    mt.locationUnits = 'pixels';
                elseif (res.getLocationUnits == javaMethod('valueOf','edu.ucsf.tsf.TaggedSpotsProtos$SpotList$LocationUnits', 2))
                    mt.locationUnits = 'um';
                end
            end
            if (res.hasNrChannels)
                mt.nrChannels = res.getNrChannels;
            end
            if (res.hasNrFrames)
                mt.nrFrames = res.getNrFrames;
            end
            if (res.hasNrPixelsX)
                mt.nrPixelsX = res.getNrPixelsX;
            end
            if (res.hasNrPixelsY)
                mt.nrPixelsY = res.getNrPixelsY;
            end
            if (res.hasNrPos)
                mt.nrPos = res.getNrPos;
            end
            if (res.hasNrSlices)
                mt.nrSlices = res.getNrSlices;
            end
            if (res.hasPixelSize)
                mt.pixelSize = res.getPixelSize;
            end
            
            
        end % mtsf
        

        % The following functions can be used as an example to write code
        % to access other fields in the tsf file
        % Performance of these functions is quite poor: calling the getX
        % function on a dataset with 550,000 took 360 seconds. 
        % Calling getXY on the same dataset took 745 seconds.
        
        % Retrieve x values in a 1D array of size (nrSpots, 1)
        function  x = getX(mt) 
            x = zeros(mt.nrSpots, 1);
            for i = 1 : mt.nrSpots
                x(i,1) = mt.spotList.get(i-1).getX;
            end           
        end  % getX
        
        % Retrieve y values in a 1D array of size (nrSpots, 1)
        function  y = getY(mt) 
            y = zeros(mt.nrSpots, 1);
            for i = 1 : mt.nrSpots
                y(i,1) = mt.spotList.get(i-1).getY;
            end           
        end  % getY
        
        % Retrieve xy values in a 2D array of size (nrSpots, 2)
        function  xy = getXY(mt) 
            xy = zeros(mt.nrSpots, 2);
            for i = 1 : mt.nrSpots
                xy(i,1) = mt.spotList.get(i-1).getX;
                xy(i,2) = mt.spotList.get(i-1).getY;
            end           
        end  % getY
        
        % 
        function s = getS(mt)
            s = zeros(mt.nrSpots, 1);
            for i = 1 : mt.nrSpots
                s(i,1) = mt.spotList.get(i-1).getSigma;
            end
        end
        
        function ch = getChannel(mt)
            ch = zeros(mt.nrSpots, 1);
            for i = 1 : mt.nrSpots
                ch(i,1) = mt.spotList.get(i-1).getChannel;
            end
        end
        
        function f = getFrame(mt)
            f = zeros(mt.nrSpots, 1);
            for i = 1 : mt.nrSpots
                f(i,1) = mt.spotList.get(i-1).getFrame;
            end
        end
        
        function p = getPos(mt)
            p = zeros(mt.nrSpots, 1);
            for i = 1 : mt.nrSpots
                p(i,1) = mt.spotList.get(i-1).getPos;
            end
        end
        
        
    end  %methods
        
end

