classdef mtsf
    %mtsf Matlab interface to tagged spot format
    %   The tagged spot format is an implementation of  
    %   Google Protocols Buffer to the storage of single molecule 
    %   fitting data such as used in super resolution techniques like
    %   STORM and PALM.  This matlab code interfaces to the Java
    %   code generated by Google Protocol Buffers based on tsf.proto
    
    properties
    end
    
    methods
        f = '/Volumes/nico/Images/20101214/D-data.tsf'
        fi = java.io.FileInputStream(f);
        ps1 = javaMethod('parseFrom', 'edu.ucsf.tsf.TaggedSpotsProtos$SpotList', fi);
        spotList = psl.getSpotList();
        spot = spotList.get(0);
        
    end
    
end

