classdef mtsf
    %mtsf Matlab interface to tagged spot format
    %   The tagged spot format is an implementation of  
    %   Google Protocols Buffer to the storage of single molecule 
    %   fitting data such as used in super resolution techniques like
    %   STORM and PALM.  This matlab code interfaces to the Java
    %   code generated by Google Protocol Buffers based on tsf.proto
    
    properties
        spotList_
        fileName_
    end
    
    methods
        function mt = mtsf(fileName)
            mt.fileName_ = fileName;
            fi = java.io.FileInputStream(mt.fileName_);
            res = javaMethod('parseFrom', 'edu.ucsf.tsf.TaggedSpotsProtos$SpotList', fi);
            mt.spotList_ = res.getSpotList();
            % spot = spotList.get(0);
        end % MtSpotTaggedFormat
        
    end
    
end

